// Lint configuration for the two hand-written JavaScript surfaces: the page
// scripts in public/, which the browser loads as plain scripts with no build
// step, and the Playwright suite in e2e/, which is type-checked TypeScript.
//
// The Go application is linted by `go vet`; nothing here touches it.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "bin/**",
      // Generated by `npm run css`, and minified onto one line.
      "public/app.css",
      "e2e/playwright-report/**",
      "e2e/test-results/**",
    ],
  },

  // Page scripts. No bundler and no module system: each file is a classic
  // script that publishes what the next one needs on `window`, so the globals
  // it defines and the ones it reads are both declared here.
  {
    files: ["public/**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // Loaded from a CDN on the endpoint page only.
        Alpine: "readonly",
        hljs: "readonly",
      },
    },
  },

  // Playwright suite. Type-aware linting, so an implicit `any` reaching an
  // assertion is an error rather than a silently weaker test.
  {
    files: ["e2e/**/*.ts"],
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname + "/e2e",
      },
    },
  },

  // This file is the only Node-side script in the repository.
  {
    files: ["eslint.config.mjs"],
    languageOptions: { globals: globals.node },
  },
);
