// Lint configuration for the two hand-written JavaScript surfaces: the page
// scripts in public/, which the browser loads as plain scripts with no build
// step, and the Playwright suite in e2e/, which is type-checked TypeScript.
//
// The Go application is linted by `go vet`; nothing here touches it.

import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  {
    ignores: [
      "**/node_modules/**",
      "bin/**",
      // Generated by `pnpm run css`, and minified onto one line.
      "public/app.css",
      "e2e/playwright-report/**",
      "e2e/test-results/**",
    ],
  },

  // The caps are measured, not chosen. Re-deriving one means running the rule
  // at max 0 and reading the highest number back. Two things make that
  // unreliable by hand: complexity words its message "has a complexity of 15"
  // while max-params and max-depth say "(3)", so a grep for one shape finds
  // nothing for the other; and a glob passed to eslint is not a glob the shell
  // expanded, so scope it with a file list rather than a pattern.
  //
  // Three ratchets, over every file linted here. Each cap sits at the worst
  // score the tree currently carries, so it holds the line rather than leaving
  // room to grow into, and a function that gains a branch has to lose one
  // somewhere. Lower them as hotspots are simplified; raising one is how a
  // ratchet stops working. `gocyclo -over 4` in CI is the Go counterpart to the
  // first of these.
  //
  // The modified variant scores a whole switch as one decision rather than one
  // per case. It changes no number here, because none of these files switch,
  // and it is stated so the rule reads the same as it does in the sibling
  // repositories rather than differing in a way that looks deliberate.
  {
    rules: {
      complexity: ["error", { max: 5, variant: "modified" }],
      "max-params": ["error", 3],
      "max-depth": ["error", 2],
    },
  },

  // Page scripts. No bundler and no module system: each file is a classic
  // script that publishes what the next one needs on `window`, so the globals
  // it defines and the ones it reads are both declared here.
  {
    files: ["public/**/*.js"],
    extends: [js.configs.recommended],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        // Loaded from a CDN on the endpoint page only.
        Alpine: "readonly",
        hljs: "readonly",
      },
    },
  },

  // Playwright suite. Type-aware linting, so an implicit `any` reaching an
  // assertion is an error rather than a silently weaker test.
  {
    files: ["e2e/**/*.ts"],
    extends: [js.configs.recommended, tseslint.configs.recommendedTypeChecked],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname + "/e2e",
      },
    },
  },

  // This file is the only Node-side script in the repository.
  {
    files: ["eslint.config.mjs"],
    languageOptions: { globals: globals.node },
  },
);
